### ISSUE TITLE
Information Centre content not visible on my smartphone

### ISSUE THREAD

**Issue by JohnAntwerp** [micado-eu/migrant_application#97] opened 2020-11-26 15:59 UTC
![image](https://user-images.githubusercontent.com/61241645/100371733-8558e800-3008-11eb-9261-2d64b7a7c4a7.png)

The content I created with e-learning leefloon is visible on my computer. If I visit this page on my Apple iPhone the content is not visible.

**Comment by JohnAntwerp** [comment] 2020-11-26 16:01
![image](https://user-images.githubusercontent.com/61241645/100372002-eed8f680-3008-11eb-9673-3db527a3dea9.png)

Screenshot iPhone with the invisble content.

**Comment by ivchicano** [comment] 2020-12-10 11:35
Looks like this bug only happens on iphone/safari, looking for a fix

**Comment by ivchicano** [comment] 2021-02-03 11:31
I can't seem to reproduce this problem in Iphone 7 plus with iOS 14.3, the descriptions display perfectly for me. I suggest clearing the website stored data (Settings >Safari > Advanced > Website data)
![micadoiphone1](https://user-images.githubusercontent.com/46921761/106740915-50c26780-661b-11eb-8a34-be63eb70507b.jpeg)
![micadoiphone2](https://user-images.githubusercontent.com/46921761/106740920-515afe00-661b-11eb-8fa2-e987939f31d6.jpeg)

**Comment by ivchicano** [comment] 2021-02-15 11:29
Considering this fixed as there has been no more feedback, closing

**Closed by ivchicano** 2021-02-15 11:29 UTC
Labels: bug
